### ISSUE TITLE
Printer WIFI page time limit?

### ISSUE THREAD

**Issue by ghost** [Printrbot/Printrhub#11]
Since nothing can be downloaded to the printer when it is on the WIFI screen, perhaps one work around is to implement a 10 second timer to revert back to the previous page - or the main Projects page. 

This would avoid people THINKING they are sending files to the printer, when in reality, IF they are on the WIFI screen, it just silently fails.  Instead of explaining it, this would all but eliminate a file upload failure due to being on that one restrictive screen.

There are other ways to solve this, but not sure of the limitations you are dealing with:
-allow uploads on that page
-explain with onscreen words "No uploads allowed in this screen"
-Having printrbot.cloud warn if they are on that black-magical screen (complicated)
--??

**Comment by mickbalaban** [comment]
fixed
