### ISSUE TITLE
Firmware Update Changes Listed by versions

### ISSUE THREAD

**Issue by ghost** [Printrbot/Printrhub#13]
Brief list of what was changed in various firmware updates.  v.14.... v.15... etc

Im a github idiot so maybe that fancy pants stuff is already happening

**Comment by mickbalaban** [comment]
Each release will from now on have list of changes, starting with build 109
https://github.com/Printrbot/Printrhub/releases/tag/109

**Comment by ghost** [comment]
Awesome!! 

On way to office ;)
Brook
