### ISSUE TITLE
Capture actual print times and adjust estimate accordingly

### ISSUE THREAD

**Issue by ururk** [Printrbot/Printrhub#15]
Feel free to ignore this suggestion, but it occurred to me...

Time estimates will always be off. They take longer than what the slicer (or in our case, the 2016 Simple) says they will take. For the Simple I haven't quantified how far they are off, but they do not seem to be accurate. The printrhub isn't at fault, since this comes from the cloud. I've printed both PLA (100% speed) and flexible filament (50% speed).

However, if there was a checksum for both prints and filament, a data table could be constructed with:

    Model checksum, Selected Filament profile checksum, Actual print time

* Anytime the model is deleted or updated, erase all rows with the old model checksum
* Anytime a specific filament profile is deleted or updated, erase all rows with the old filament checksum
* A new row would be added when the print finished, or updated (and averaged) if a row already existed
* When printing, if the checksums match up, use this actual print time instead of estimated

**Comment by mickbalaban** [comment]
we decided to remove estimated print time from the print screen since it was not very accurate. We may add this feature back in when we have a better implementation.

https://github.com/Printrbot/Printrhub/commit/6a3a4a97bd44ad0d5bfb6b0256bbe7bd95d63e87
