### ISSUE TITLE
Projects showing up multiple times

### ISSUE THREAD

**Issue by ururk** [Printrbot/Printrhub#17]
I don't know if this is due to the cloud platform sending different project IDs for the same project, but when I push a project to the 2016 Simple it sometimes is listed multiple times. Deleting one instance of a project does not clear out the other ("identical") instances.

**Comment by bmv437** [comment]
I have experienced the same issue.

**Comment by ururk** [comment]
I should post a slight correction - at least for me - when one of the duplicate projects are deleted, all instances disappear.

**Comment by mickbalaban** [comment]
this should be fixed now. It will be deployed with next firmware update
